---
- name: Fix Kubernetes Node Issues
  hosts: master,workers
  become: yes
  tasks:
    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Disable Firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: stopped
        enabled: no

    - name: Open required Kubernetes ports if firewalld is running
      ansible.builtin.firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
      loop:
        - 6443/tcp
        - 10250/tcp
      when: "'firewalld.service' in ansible_facts.services and ansible_facts.services['firewalld.service'].state == 'running'"
      notify: Reload firewalld

    - name: Disable Swap
      ansible.builtin.command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: Remove swap entry from /etc/fstab
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '^(.*swap.*)$'
        replace: '# \1'

    - name: Ensure /etc/hosts contains master and worker nodes
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
        state: present
      loop:
        - "192.168.1.171 k8smaster"
        - "192.168.1.177 k8sworker1"
        - "192.168.1.178 k8sworker2"

    - name: Ensure containerd config.toml exists
      ansible.builtin.command: containerd config default > /etc/containerd/config.toml
      args:
        creates: /etc/containerd/config.toml

    - name: Set SystemdCgroup in containerd config
      ansible.builtin.replace:
        path: /etc/containerd/config.toml
        regexp: 'SystemdCgroup = false'
        replace: 'SystemdCgroup = true'

    - name: Restart and enable containerd
      ansible.builtin.systemd:
        name: containerd
        state: restarted
        enabled: yes

    - name: Verify containerd is running
      ansible.builtin.command: systemctl is-active containerd
      register: containerd_status
      failed_when: containerd_status.stdout != 'active'

  handlers:
    - name: Reload firewalld
      ansible.builtin.command: firewall-cmd --reload
