- name: Kubernetes Worker Node Setup
  hosts: workers
  become: true
  tasks:
    # 1. Docker 공식 레포지토리 추가 (containerd 설치용)
    - name: Docker 공식 레포지토리 추가
      shell: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo

    # 2. Kubernetes 공식 레포지토리 추가 (v1.28.15 고정)
    - name: Kubernetes 공식 레포지토리 추가
      copy:
        dest: /etc/yum.repos.d/kubernetes.repo
        content: |
          [kubernetes]
          name=Kubernetes
          baseurl=https://pkgs.k8s.io/core:/stable:/v1.28/rpm/
          enabled=1
          gpgcheck=1
          repo_gpgcheck=1
          gpgkey=https://pkgs.k8s.io/core:/stable:/v1.28/rpm/repodata/repomd.xml.key
      register: k8s_repo_added

    # 3. 패키지 캐시 업데이트 (레포지토리 추가 후 필수)
    - name: 패키지 캐시 업데이트
      shell: yum clean all && yum makecache
      when: k8s_repo_added.changed

    # 4. 필요한 패키지 설치
    - name: 필수 패키지 설치
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    # 5. containerd 설치
    - name: containerd 설치
      yum:
        name: containerd.io
        state: present

    - name: containerd 서비스 활성화 및 시작
      systemd:
        name: containerd
        state: started
        enabled: true

    # 6. Kubernetes 패키지 설치 (v1.28.15 고정)
    - name: Kubernetes 패키지 설치 (kubeadm, kubelet v1.28.15)
      yum:
        name:
          - kubeadm-1.28.15
          - kubelet-1.28.15
        state: present
        disable_excludes: kubernetes

    - name: Kubelet 서비스 활성화
      systemd:
        name: kubelet
        enabled: true

    # 7. 방화벽 설정 추가
    - name: Kubernetes Worker 방화벽 규칙 추가
      firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
      with_items:
        - 10250/tcp
        - 30000-32767/tcp

    - name: 방화벽 재시작
      service:
        name: firewalld
        state: restarted
