---
- name: Deploy Nginx on Kubernetes
  hosts: master
  become: yes
  tasks:
    - name: Copy Kubernetes manifests to Master Node
      copy:
        src: /home/runner/actions-runner/_work/k8s/k8s/manifests/nginx-deployment.yml
        dest: "/tmp/nginx-deployment.yml"

    - name: Apply Kubernetes manifests (Deployment & Service)
      command: kubectl apply -f /tmp/nginx-deployment.yml
