- name: Kubernetes Worker Node Setup
  hosts: workers
  become: true
  tasks:
    - name: 필요한 패키지 설치
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present
      when: "'overlay2' not in ansible_facts['cmdline']['containerd']"

    - name: containerd 설치
      yum:
        name: containerd.io
        state: present

    - name: containerd 서비스 활성화 및 시작
      systemd:
        name: containerd
        state: started
        enabled: true

    - name: Kubernetes 패키지 설치 (kubeadm, kubelet)
      yum:
        name:
          - kubeadm
          - kubelet
        state: present

    - name: Kubelet 서비스 활성화
      systemd:
        name: kubelet
        enabled: true

    - name: 방화벽이 실행 중인지 확인
      command: systemctl is-active firewalld
      register: firewalld_status
      changed_when: false
      ignore_errors: true

    - name: Kubernetes Worker 방화벽 규칙 추가 (firewalld 사용 시)
      firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
      with_items:
        - 10250/tcp
        - 30000-32767/tcp
      when: firewalld_status.rc == 0

    - name: 방화벽 재시작 (firewalld 사용 시)
      service:
        name: firewalld
        state: restarted
      when: firewalld_status.rc == 0
