---
- name: Deploy Nginx on Kubernetes
  hosts: master
  become: yes
  tasks:
    - name: Apply Kubernetes manifests (Deployment & Service)
      command: kubectl apply -f /home/runner/actions-runner/_work/k8s/k8s/manifests/nginx-deployment.yml
