- name: Setup SSH Key Authentication on Ansible Server
  hosts: ansible_runner
  become: yes
  tasks:
    - name: Ensure SSH directory exists on Ansible Server
      file:
        path: /home/runner/.ssh
        state: directory
        mode: '0700'
        owner: runner
        group: runner

    - name: Generate SSH key for runner user if not exists
      command: ssh-keygen -t rsa -b 4096 -f /home/runner/.ssh/id_rsa -N ""
      args:
        creates: /home/runner/.ssh/id_rsa
      become_user: runner

- name: Configure SSH Known Hosts on Master and Worker Nodes
  hosts: master, workers
  become: yes
  tasks:
    - name: Ensure SSH directory exists on Target Nodes
      file:
        path: /root/.ssh
        state: directory
        mode: '0700'
        owner: root
        group: root

    - name: Ensure known_hosts file exists
      file:
        path: /root/.ssh/known_hosts
        state: touch
        mode: '0644'
        owner: root
        group: root

    - name: Add Ansible Server's SSH host key to known_hosts
      shell: "ssh-keyscan -H {{ hostvars['ansible_runner']['ansible_host'] }} >> /root/.ssh/known_hosts"
      become_user: root

    - name: Test SSH connection from Ansible Server to Target Nodes
      command: ssh -o BatchMode=yes root@{{ ansible_host }} exit
      register: ssh_test
      ignore_errors: yes

    - name: Debug SSH test results
      debug:
        msg: "SSH Connection to {{ ansible_host }}: {{ 'Success' if ssh_test.rc == 0 else 'Failed' }}"
