- name: Setup SSH Key Authentication on Ansible Server
  hosts: ansible_runner
  become: yes
  tasks:
    - name: Ensure SSH directory exists on Ansible Server
      file:
        path: /home/runner/.ssh
        state: directory
        mode: '0700'
        owner: runner
        group: runner

    - name: Generate SSH key for runner user if not exists
      command: ssh-keygen -t rsa -b 4096 -f /hom
